version: "2"
linters:
  enable:
    - gosec     # Checks for common security issues in Go code.
    - misspell  # Finds and corrects spelling mistakes in comments and strings.
    - revive    # Provides style and best practice suggestions.
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      severity: warning
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go$
        linters:
          - gosec
      - path: example
        linters:
          - gosec
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true