// Code generated by MockGen. DO NOT EDIT.
// Source: ./auth.go

// Package sftp_mocks is a generated GoMock package.
package sftp_mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ssh "golang.org/x/crypto/ssh"
)

// MockAuthenticationHandler is a mock of AuthenticationHandler interface.
type MockAuthenticationHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationHandlerMockRecorder
}

// MockAuthenticationHandlerMockRecorder is the mock recorder for MockAuthenticationHandler.
type MockAuthenticationHandlerMockRecorder struct {
	mock *MockAuthenticationHandler
}

// NewMockAuthenticationHandler creates a new mock instance.
func NewMockAuthenticationHandler(ctrl *gomock.Controller) *MockAuthenticationHandler {
	mock := &MockAuthenticationHandler{ctrl: ctrl}
	mock.recorder = &MockAuthenticationHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationHandler) EXPECT() *MockAuthenticationHandlerMockRecorder {
	return m.recorder
}

// GetAuthMethods mocks base method.
func (m *MockAuthenticationHandler) GetAuthMethods() ([]ssh.AuthMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthMethods")
	ret0, _ := ret[0].([]ssh.AuthMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthMethods indicates an expected call of GetAuthMethods.
func (mr *MockAuthenticationHandlerMockRecorder) GetAuthMethods() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthMethods", reflect.TypeOf((*MockAuthenticationHandler)(nil).GetAuthMethods))
}

// ValidateCredentials mocks base method.
func (m *MockAuthenticationHandler) ValidateCredentials() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCredentials")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCredentials indicates an expected call of ValidateCredentials.
func (mr *MockAuthenticationHandlerMockRecorder) ValidateCredentials() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCredentials", reflect.TypeOf((*MockAuthenticationHandler)(nil).ValidateCredentials))
}
