// Code generated by MockGen. DO NOT EDIT.
// Source: ./connection.go

// Package sftp_mocks is a generated GoMock package.
package sftp_mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sftp "github.com/pkg/sftp"
)

// MockConnectionManager is a mock of ConnectionManager interface.
type MockConnectionManager struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionManagerMockRecorder
}

// MockConnectionManagerMockRecorder is the mock recorder for MockConnectionManager.
type MockConnectionManagerMockRecorder struct {
	mock *MockConnectionManager
}

// NewMockConnectionManager creates a new mock instance.
func NewMockConnectionManager(ctrl *gomock.Controller) *MockConnectionManager {
	mock := &MockConnectionManager{ctrl: ctrl}
	mock.recorder = &MockConnectionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionManager) EXPECT() *MockConnectionManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConnectionManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConnectionManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnectionManager)(nil).Close))
}

// GetConnection mocks base method.
func (m *MockConnectionManager) GetConnection(ctx context.Context) (*sftp.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx)
	ret0, _ := ret[0].(*sftp.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockConnectionManagerMockRecorder) GetConnection(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockConnectionManager)(nil).GetConnection), ctx)
}

// ReleaseConnection mocks base method.
func (m *MockConnectionManager) ReleaseConnection(client *sftp.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseConnection", client)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseConnection indicates an expected call of ReleaseConnection.
func (mr *MockConnectionManagerMockRecorder) ReleaseConnection(client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseConnection", reflect.TypeOf((*MockConnectionManager)(nil).ReleaseConnection), client)
}
